apiVersion: v1
kind: Service
metadata:
  name: my-deployment-service
spec:
  selector:
    app: my-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
  type: NodePort
